name: notarize-docker-image-bom

on:
  push:
    branches: [main]

jobs:
  notarize-docker-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      # Pull an image to notarize; This is where you'd build your local image instead using your preferred method
      - name: debug
        run: docker pull codenotary/cas:bom-docker
        shell: bash


      - name: Notarize Docker image
        #--> Run the GitHub action
        # uses: codenotary/cas-notarize-docker-image-github-action@v1.0.0
        uses: codenotary/cas-notarize-docker-image-bom-github-action@main
        with:
          # make it notarize it's own Docker image B-)
          asset: docker://codenotary/cas:bom-docker
          cas_api_key: ${{ secrets.CAS_API_KEY }}
